IndicesFacadeService:
    Db:
        LogsConnString:
            settings-key: IndicesFacadeService-LogsConnString
            types:
              - AzureTableStorage

    RabbitMqSettings:
        ConnectionString:
            settings-key: IndicesFacadeService-ConnectionString
        SubscribeCryptoIndicesTickPricesExchange:
            settings-key: IndicesFacadeService-SubscribeCryptoIndicesTickPricesExchange
        PublishIndicesUpdatesExchange:
            settings-key: IndicesFacadeService-PublishIndicesUpdatesExchange
        PublishIndicesHistoryUpdatesExchange:
            settings-key: IndicesFacadeService-PublishIndicesHistoryUpdatesExchange

CryptoIndexServiceClient:
  Instances:
    settings-key: CryptoIndexService-Instances
    types:
    - JsonArray

SlackNotifications:
    AzureQueue:
        ConnectionString:
            settings-key: SlackNotificationsConnString
            types:
                - AzureTableStorage
        QueueName:
            settings-key: SlackQueueName

MonitoringServiceClient:
    MonitoringServiceUrl:
        settings-key: MonitoringServiceUrl

